# Uncomment the next line to define a global platform for your project
platform :ios, '13.4'

target 'Tracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tracker
  pod 'YandexMobileMetrica/Dynamic', '4.5.2'

  target 'TrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
